# Generated by Django 2.1.3 on 2018-11-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_family_location_product_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='product',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
